const CATEGORIES = {
  None: "None",
  Templates: "Templates",
  Creators: "Creators",
  "Components": "Components",
  "Static files": "Static files",
  "Guides": "Guides",
};

export const DOCS: Record<string, any> = {
  categories: CATEGORIES,
  docs: [
    {
      title: "Installation",
      md: "installation.md",
      path: "installation.html",
      weight: 1,
      category: CATEGORIES.None,
    },
    {
      title: "Quickstart",
      md: "quickstart.md",
      path: "quickstart.html",
      weight: 2,
      category: CATEGORIES.None,
    },
    {
      title: "Known limitations",
      md: "limitations.md",
      path: "limitations.html",
      weight: 3,
      category: CATEGORIES.None,
    },
    {
      title: "About templates",
      md: "about-templates.md",
      path: "about-templates.html",
      weight: 1,
      category: CATEGORIES.Templates,
    },
    {
      title: "Text interpolation",
      md: "text-interpolation.md",
      path: "text-interpolation.html",
      weight: 2,
      category: CATEGORIES.Templates,
    },
    {
      title: "Attributes evaluation",
      md: "attributes-evaluation.md",
      path: "attributes-evaluation.html",
      weight: 3,
      category: CATEGORIES.Templates,
    },
    {
      title: "Contionnally display elements",
      md: "cond-display.md",
      path: "conditionnally-display-elements.html",
      weight: 4,
      category: CATEGORIES.Templates,
    },
    {
      title: "Loops",
      md: "loops.md",
      path: "templates-loops.html",
      weight: 5,
      category: CATEGORIES.Templates,
    },
    {
      title: "About creators",
      md: "about-creators.md",
      path: "about-creators.html",
      weight: 1,
      category: CATEGORIES.Creators,
    },
    {
      title: "Using components",
      md: "using-components.md",
      path: "using-components.html",
      weight: 1,
      category: CATEGORIES.Components,
    },
    {
      title: "How are static files handled ?",
      md: "how-sf-handled.md",
      path: "how-are-static-files-handled.html",
      weight: 1,
      category: CATEGORIES["Static files"],
    },
    {
      title: "Having a reactive runtime",
      md: "dynamic-runtime.md",
      path: "having-a-dynamic-runtime.html",
      weight: 1,
      category: CATEGORIES.Guides,
    },
  ],
};
